"""
Have the user enter a percentage and return the letter grade associated with the percentage

Use a standard 10 point grading scale

100-90:A
89-80: B
79- 70: C
69 - 0 : F


PART 2

Have the inputed grade be a s rtandom number generated by the computer and print the grade
"""
import random

percentage_grade = int(input('What percentage did you get? >> '))

if percentage_grade >= 90:
    print('Your grade is an A')

elif percentage_grade >= 80:
    print('Your grade is an B')

elif percentage_grade >=70:
    print('Your grade is a C')

else:
    print('Your grade is a F for FAIL.')
